version: '3'
services:
  backend:
    build:  
      context: ./backend
    container_name: french-task-backend
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./backend:/app

  frontend:
    build:  
      context: ./frontend
    container_name: french-task-frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    command: npm run dev